### ISSUE TITLE
Error: importers.pdc: aliquotrunmetadata.json

### ISSUE THREAD

**Issue by joeflack4** [cancerDHC/ccdh-terminology-service#114]
## Description
Running the importer causes errors.

## Error message
```
INFO:ccdh.importers.pdc:Loading aliquotrunmetadata.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/ccdh/importers/importer.py", line 221, in <module>
    Importer.import_all()
  File "/app/ccdh/importers/importer.py", line 213, in import_all
    Importer(neo4j_graph()).import_node_attributes(PdcImporter.read_data_dictionary())
  File "/app/ccdh/importers/pdc.py", line 29, in read_data_dictionary
    entity = json.loads(file.read_text())
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## Steps to reproduce
1. Follow the setup in README.md
2. Get to the part where you run `python -m ccdh.importers.importer`

## Attachments
[aliquotrunmetadata.json.zip](https://github.com/cancerDHC/ccdh-terminology-service/files/7445747/aliquotrunmetadata.json.zip)

**Comment by joeflack4** [comment]
@wdduncan I ran, but I didn't have an error. I'm wondering if you (a) don't have this file, or (b) have it, but it is malformed.

Can you check that you have the following file:
`crdc-nodes/PDC-Public/documentation/prod/json/aliquotrunmetadata.json`

And if so, can you check that its contents match:

**Comment by wdduncan** [comment]
@joeflack4 I have the file, but it doesn't have any data. Here the contents of my file:
```
version https://git-lfs.github.com/spec/v1
oid sha256:24c0de9335c06694a6a5f72afad5d97a7dbe5addc8439532f73aa32ac7981ec1
size 4040
```
How can I update?

**Comment by joeflack4** [comment]
Looks like we fixed this. Not sure what was wrong initially.
