### ISSUE TITLE
Bug: setup issue: `ModuleNotFoundError`: `linkml_model`, `linkml.utils.slot`

### ISSUE THREAD

**Issue by joeflack4** [cancerDHC/ccdh-terminology-service#28]
## Description
When following the instructions in `quick_start.md`, I encounter `ModuleNotFoundError`s when running the `docker-compose up` command.

## Short errors
1. `ModuleNotFoundError: No module named 'linkml_model'`
2. `ModuleNotFoundError: No module named 'linkml.utils.slot'`

### 1: `linkml_model`
Shell error:
`ERROR: for ccdh-api  Container "8b435e56d182" is unhealthy.`

```
(cd docker && docker-compose up)
Creating network "docker_default" with the default driver
Creating volume "docker_ccdh-neo4j" with default driver
Pulling ccdh-neo4j (neo4j:4.1.3)...
4.1.3: Pulling from library/neo4j
b4d181a07f80: Pull complete
3ee45ae97306: Pull complete
567d410fadc4: Pull complete
ad7fd4930617: Pull complete
7d320042d02a: Pull complete
be5f9d589606: Pull complete
973098f6f4e2: Pull complete
603e26c5e3e5: Pull complete
Digest: sha256:4d0d4bc3e8a636f74900b0817c95921bb398efcffc646ecf87658cb9f1e9723b
Status: Downloaded newer image for neo4j:4.1.3
Creating neo4j ... done
ERROR: for ccdh-api  Container "8b435e56d182" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

Docker logs:
```
Creating a virtualenv for this project...
Pipfile: /app/Pipfile
Using /usr/local/bin/python3.8 (3.8.11) to create virtualenv...
⠋ Creating virtual environment...created virtual environment CPython3.8.11.final.0-64 in 1315ms
creator CPython3Posix(dest=/root/.local/share/virtualenvs/app-4PlAip0Q, clear=False, no_vcs_ignore=False, global=False)
seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
added seed packages: pip==21.1.2, setuptools==57.0.0, wheel==0.36.2
activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
✔ Successfully created virtual environment!
Virtualenv location: /root/.local/share/virtualenvs/app-4PlAip0Q
Loading .env environment variables...
Traceback (most recent call last):
File "/usr/local/bin/uvicorn", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 371, in main
run(app, **kwargs)
File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 393, in run
server.run()
File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 50, in run
loop.run_until_complete(self.serve(sockets=sockets))
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 57, in serve
config.load()
File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 318, in load
self.loaded_app = import_from_string(self.app)
File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 25, in import_from_string
raise exc from None
File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 22, in import_from_string
module = importlib.import_module(module_str)
File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 843, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/app/./ccdh/api/app.py", line 7, in <module>
from ccdh.api.routers import mappings, permissible_values, enumerations, models, ccdh_concept_references
File "/app/./ccdh/api/routers/mappings.py", line 1, in <module>
from sssom.sssom_datamodel import Mapping as SssomMapping
File "/src/sssom/sssom/__init__.py", line 1, in <module>
from .util import parse, collapse, dataframe_to_ptable, filter_redundant_rows, group_mappings, compare_dataframes
File "/src/sssom/sssom/util.py", line 11, in <module>
from sssom.datamodel_util import MappingSetDiff, EntityPair
File "/src/sssom/sssom/datamodel_util.py", line 5, in <module>
from sssom.sssom_document import MappingSetDocument
File "/src/sssom/sssom/sssom_document.py", line 1, in <module>
from .sssom_datamodel import MappingSet, Mapping, Entity
File "/src/sssom/sssom/sssom_datamodel.py", line 14, in <module>
from linkml_model.meta import EnumDefinition, PermissibleValue, PvFormulaOptions
ModuleNotFoundError: No module named 'linkml_model'
```

### 2: `linkml.utils.slot`
Shell error:
```
ERROR: for ccdh-api  Container "1b132121e048" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

Docker error logs:
```
Creating a virtualenv for this project...
Pipfile: /app/Pipfile
Using /usr/local/bin/python3.8 (3.8.11) to create virtualenv...
⠇ Creating virtual environment...created virtual environment CPython3.8.11.final.0-64 in 1417ms
creator CPython3Posix(dest=/root/.local/share/virtualenvs/app-4PlAip0Q, clear=False, no_vcs_ignore=False, global=False)
seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
added seed packages: pip==21.1.2, setuptools==57.0.0, wheel==0.36.2
activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
✔ Successfully created virtual environment!
Virtualenv location: /root/.local/share/virtualenvs/app-4PlAip0Q
Loading .env environment variables...
Traceback (most recent call last):
File "/usr/local/bin/uvicorn", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 371, in main
run(app, **kwargs)
File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 393, in run
server.run()
File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 50, in run
loop.run_until_complete(self.serve(sockets=sockets))
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 57, in serve
config.load()
File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 318, in load
self.loaded_app = import_from_string(self.app)
File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 25, in import_from_string
raise exc from None
File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 22, in import_from_string
module = importlib.import_module(module_str)
File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 843, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/app/./ccdh/api/app.py", line 7, in <module>
from ccdh.api.routers import mappings, permissible_values, enumerations, models, ccdh_concept_references
File "/app/./ccdh/api/routers/mappings.py", line 1, in <module>
from sssom.sssom_datamodel import Mapping as SssomMapping
File "/src/sssom/sssom/__init__.py", line 1, in <module>
from .util import parse, collapse, dataframe_to_ptable, filter_redundant_rows, group_mappings, compare_dataframes
File "/src/sssom/sssom/util.py", line 11, in <module>
from sssom.datamodel_util import MappingSetDiff, EntityPair
File "/src/sssom/sssom/datamodel_util.py", line 5, in <module>
from sssom.sssom_document import MappingSetDocument
File "/src/sssom/sssom/sssom_document.py", line 1, in <module>
from .sssom_datamodel import MappingSet, Mapping, Entity
File "/src/sssom/sssom/sssom_datamodel.py", line 16, in <module>
from linkml.utils.slot import Slot
ModuleNotFoundError: No module named 'linkml.utils.slot'
```

## Things I tried
1. Different branch "improvement-batch": I checked and this branch was closed. I decided not to try and dig up an old tag. I also merged the latest code, but no changes had been made since I forked.
2. Installing without docker: I tried this and I got the same results.
3. Updating `Pipfile` w/ missing/bad requirements: I decided to add the line `linkml-model = "*"`. This fixed the first `linkml_model` `ModuleNotFoundError`! But when running `docker-compose up` again, I got the `linkml.utils.slot` error.

## Possible solutions
Similar to what I tried in "things I tried" (3), this may just be an issue of other **linkml** modules not having been added to the `Pipfile`. @jiaola Let's discuss when you return!

**Comment by joeflack4** [comment]
This has been fixed! Forgot to close, so closing it now.
