### ISSUE TITLE
Bug: GDC Importer fhir.hotecosystem.org SSL error

### ISSUE THREAD

**Issue by joeflack4** [cancerDHC/ccdh-terminology-service#46]
## Description
I haven't looked super deeply into this error message yet, but this is a new failure I am seeing that is coming up both during (1) tests / build checks, and (2) when using the GDC importer. I'm not 100% sure yet because I haven't looked deeply into the issue, but it looks to me like their SSL certificate is now invalid.

<img width="1237" alt="Screen Shot 2021-07-25 at 7 57 34 PM" src="https://user-images.githubusercontent.com/13045020/126918350-f6dde9d0-4b8a-4a32-a833-fdc635812a74.png">

### Short error
```py
requests.exceptions.SSLError: HTTPSConnectionPool(host='fhir.hotecosystem.org', port=443): Max retries exceeded with url: /terminology/cadsr/ValueSet/2513915 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
```

### Long error
```py
/Users/joeflack4/virtualenvs/ccdh-terminology-service/bin/python3 /Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 63472 --file /Users/joeflack4/projects/ccdh-terminology-service/ccdh/importers/importer.py
/Applications/PyCharm.app/Contents/helpers/pydev/_pydevd_bundle/pydevd_resolver.py:127: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if found.get(name) is not 1:
pydev debugger: process 4252 is connecting

Connected to pydev debugger (build 181.5540.34)
INFO:ccdh.importers.crcd_h:Retrieving CCDH Model YAML: https://raw.githubusercontent.com/cancerDHC/ccdhmodel/main/src/schema/ccdhmodel.yaml
INFO:ccdh.importers.gdc:Loading /Users/joeflack4/projects/ccdh-terminology-service/data/data_dictionary/gdc/current.json
Traceback (most recent call last):
  File "/Users/joeflack4/virtualenvs/ccdh-terminology-service/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/joeflack4/virtualenvs/ccdh-terminology-service/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/joeflack4/virtualenvs/ccdh-terminology-service/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/joeflack4/virtualenvs/ccdh-terminology-service/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/joeflack4/virtualenvs/ccdh-terminology-service/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/joeflack4/virtualenvs/ccdh-terminology-service/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joeflack4/virtualenvs/ccdh-terminology-service/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/joeflack4/virtualenvs/ccdh-terminology-service/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/joeflack4/virtualenvs/ccdh-terminology-service/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fhir.hotecosystem.org', port=443): Max retries exceeded with url: /terminology/cadsr/ValueSet/2513915 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/joeflack4/projects/ccdh-terminology-service/ccdh/importers/importer.py", line 218, in <module>
    Importer(neo4j_graph()).import_node_attributes(GdcImporter.read_data_dictionary())
  File "/Users/joeflack4/projects/ccdh-terminology-service/ccdh/importers/gdc.py", line 72, in read_data_dictionary
    value_desc = GdcImporter.\
  File "/Users/joeflack4/projects/ccdh-terminology-service/ccdh/importers/gdc.py", line 33, in get_value_descriptions_from_cadsr
    values = get_cadsr_values(cde_id)
  File "/Users/joeflack4/projects/ccdh-terminology-service/ccdh/importers/cadsr.py", line 13, in get_cadsr_values
    value_set = ValueSet.read(cde_id, smart.server)
  File "/Users/joeflack4/virtualenvs/ccdh-terminology-service/lib/python3.9/site-packages/fhirclient/models/fhirabstractresource.py", line 83, in read
    instance = cls.read_from(path, server)
  File "/Users/joeflack4/virtualenvs/ccdh-terminology-service/lib/python3.9/site-packages/fhirclient/models/fhirabstractresource.py", line 102, in read_from
    ret = server.request_json(path)
  File "/Users/joeflack4/virtualenvs/ccdh-terminology-service/lib/python3.9/site-packages/fhirclient/server.py", line 163, in request_json
    res = self._get(path, headers, nosign)
  File "/Users/joeflack4/virtualenvs/ccdh-terminology-service/lib/python3.9/site-packages/fhirclient/server.py", line 190, in _get
    res = self.session.get(url, headers=headers)
  File "/Users/joeflack4/virtualenvs/ccdh-terminology-service/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Users/joeflack4/virtualenvs/ccdh-terminology-service/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/joeflack4/virtualenvs/ccdh-terminology-service/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/joeflack4/virtualenvs/ccdh-terminology-service/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='fhir.hotecosystem.org', port=443): Max retries exceeded with url: /terminology/cadsr/ValueSet/2513915 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
```

## Possible solutions
A. They fix the issue, if it is indeed fully on their end.

B. We ignore the SSL warning and try and programmatically get around and fetch data / do whatever we need from this resource regardless.

C. ???

**Comment by joeflack4** [comment]
Dazhi mentioned that this HOT ecosystem server is one that we manage, and the Certbot certificate probably expired.

**Comment by jiaola** [comment]
Fixed on hotecosystem.org
