### ISSUE TITLE
GDC Importer errors & warnings

### ISSUE THREAD

**Issue by joeflack4** [cancerDHC/ccdh-terminology-service#55]
## Description
While running `importer.py`, the GDC importer (`Importer(neo4j_graph()).import_node_attributes(GdcImporter.read_data_dictionary())`) produces warnings and errors.

## Warnings
```py
INFO:ccdh.importers.gdc:Loading /Users/joeflack4/projects/ccdh-terminology-service/data/data_dictionary/gdc/current.json
WARNING:ccdh.importers.gdc:CDE ID contains no values: 7050286
WARNING:ccdh.importers.gdc:CDE ID contains no values: 3226275
WARNING:ccdh.importers.gdc:CDE ID contains no values: 6161034
WARNING:ccdh.importers.gdc:CDE ID contains no values: 5432604
WARNING:ccdh.importers.gdc:CDE ID contains no values: 2975232
WARNING:ccdh.importers.gdc:CDE ID contains no values: 7068995
INFO:ccdh.importers.importer:Importing NodeAttribute GDC.Aggregated Somatic Mutation.batch_id ...
```

### Short error message
`KeyError: 'permissible_values'`

### Long error message
```py
INFO:ccdh.importers.gdc:Loading /Users/joeflack4/projects/ccdh-terminology-service/data/data_dictionary/gdc/current.json
...
INFO:ccdh.importers.importer:Importing NodeAttribute GDC.Aggregated Somatic Mutation.batch_id ...
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/joeflack4/projects/ccdh-terminology-service/ccdh/importers/importer.py", line 222, in <module>
    Importer.import_all()
  File "/Users/joeflack4/projects/ccdh-terminology-service/ccdh/importers/importer.py", line 215, in import_all
    Importer(neo4j_graph()).import_node_attributes(GdcImporter.read_data_dictionary())
  File "/Users/joeflack4/projects/ccdh-terminology-service/ccdh/importers/importer.py", line 60, in import_node_attributes
    self.import_node_attribute(node_attribute)
  File "/Users/joeflack4/projects/ccdh-terminology-service/ccdh/importers/importer.py", line 42, in import_node_attribute
    permissible_values = node_attribute['permissible_values']
KeyError: 'permissible_values'
```

**Comment by joeflack4** [comment]
Currently working on this. I think I just need to uncomment `permissible_values` at a certain location, but I'm not sure if this is what we want. I'll make a pull request.
